import os.path


#
# Simple settings file interface
# Assuming the file is always generated by this interface and thus has correct syntax
#

# Default settings
settings = dict(AutoFSS=False, DiscoveryScan=True, StartKey='home', EndKey='end', RefuelThreshold=40)
CFGFILE = "./EDAutopilot.cfg"


def _readSettings():
    if os.path.isfile(CFGFILE):
        f = open(CFGFILE, "r")
        for line in f:
            key, value = line.split('=')
            settings[key] = value[0:-1]
        f.close()
    else:
        _writeSettings()


def _writeSettings(dictionary=None):
    if dictionary is None:
        dictionary = settings
    f = open(CFGFILE, "w")
    for key in dictionary:
        f.write('{}={}\n'.format(key, dictionary[key]))
    f.close()
    if dictionary is not settings:
        _on_change_all()


def _on_change(key, val=None):
    from dev_autopilot import logger
    from dev_tray import updateSettings
    valStr = ""
    if val is not None:
        valStr = "to {}".format(val)

    logger.info("Setting {} changed value {}".format(key, valStr))
    updateSettings(key)


def _on_change_all():  # All or most keys changed value
    _readSettings()
    for key in settings:
        _on_change(key)


def setOption(key, value):  # Not very efficient, but pretty safe
    _readSettings()
    settings[key] = value
    _writeSettings()
    _on_change(key, value)


def getOption(key):
    _readSettings()
    val = settings[key]
    if val == "False":
        return False
    return settings[key]


def getOptions():
    _readSettings()
    return settings
