import os.path


#
# Simple settings file interface
# Assuming the file is always generated by this interface and thus has correct syntax
#


settings = dict(AutoFSS=False, DiscoveryScan=True, StartKey='home', EndKey='end')  # Default settings
CFGFILE = "./EDAutopilot.cfg"


def __readSettings():
    if os.path.isfile(CFGFILE):
        f = open(CFGFILE, "r")
        for line in f:
            key, value = line.split('=')
            settings[key] = value[0:-1]
        f.close()
    else:
        __writeSettings()


def __writeSettings(dictionary=None):
    if dictionary is None:
        dictionary = settings
    f = open(CFGFILE, "w")
    for key in dictionary:
        f.write('{}={}\n'.format(key, dictionary[key]))
    f.close()
    if dictionary is not settings:
        on_change_all()


def on_change(key, val=None):
    from dev_autopilot import logger
    from dev_tray import updateSettings
    valstr = ""
    if val is not None:
        valstr = "to {}".format(val)

    logger.info("Key {} changed value {}".format(key, valstr))  # Maybe
    updateSettings(key)


def on_change_all():  # All or most keys changed value
    __readSettings()
    for key in settings:
        on_change(key)


def setOption(key, value):  # Not very efficient, but pretty safe
    __readSettings()
    settings[key] = value
    __writeSettings()
    on_change(key, value)


def getOption(key):
    __readSettings()
    val = settings[key]
    if val == "False":
        return False
    return settings[key]

